### ISSUE TITLE
Executable does not work when not installed globally 

### ISSUE THREAD

**Issue by tmpfs** [mikeal/node.couchapp.js#85]
Running this `node_modules/.bin/couchapp`, generates:

```
module.js:340
    throw err;
          ^
Error: Cannot find module './main.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/cyberfunk/git/clients/socialally/sa-registry/node_modules/.bin/couchapp:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Because `npm` adds `node_modules/.bin` to PATH when executing scripts then it will not work in scripts that just want to reference `couchapp` for a locally installed version. 

This is easily fixed with backward compatbility, if you will accept a pull request I will patch it.

**Comment by tmpfs** [comment]
Nearly two years to the day, closing as won't fix.
